CMAKE_MINIMUM_REQUIRED(VERSION 3.8)


SET(CMAKE_ECLIPSE_EXECUTABLE /opt/eclipse/eclipse)

SET(CMAKE_ECLIPSE_GENERATE_LINKED_RESOURCES ON)

SET(CMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT ON)

SET(CMAKE_ECLIPSE_MAKE_ARGUMENTS)

# SET(CMAKE_ECLIPSE_VERSION 4.5)
