CMAKE_MINIMUM_REQUIRED(VERSION 3.8)


FIND_PROGRAM(ECLIPSE_PATH eclipse HINTS ENV PATH)

IF(NOT ECLIPSE_PATH)

	MESSAGE(FATAL_ERROR "Eclipse not found")

ELSE(NOT ECLIPSE_PATH)

	MESSAGE(STATUS "Eclipse installed at ${ECLIPSE_PATH}")

ENDIF(NOT ECLIPSE_PATH)


SET(CMAKE_ECLIPSE_EXECUTABLE ${ECLIPSE_PATH})

SET(CMAKE_ECLIPSE_GENERATE_LINKED_RESOURCES ON)

SET(CMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT ON)

# SET(CMAKE_ECLIPSE_VERSION 4.5)
