CMAKE_MINIMUM_REQUIRED(VERSION 3.8)


# Create file listing

FUNCTION(LIST_FILES GLOB_EXPRESSION RETVAL)

	FILE(GLOB RESULT LIST_DIRECTORIES FALSE ${GLOB_EXPRESSION})

	SET(${RETVAL} ${RESULT} PARENT_SCOPE)

ENDFUNCTION(LIST_FILES)
